//register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"user1",
    "email":"user1@gmail.com",
    "password":"user1"
    "monthlyBudget":"20000",
    "role":"USER"
}



###
// login

POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"user1"
}


###
//logout

GET http://localhost:4000/common-api/logout 


###
//add expense
POST http://localhost:4000/expense-api/expense
Content-Type: application/json

{
  "title": "job",
  "amount": 15000,
  "type": "INCOME",
  "category": "SALARY",
  "description": "Shopping with hf",
  "date":"2026-04-05T08:03:56.921+00:00"
}



###
//Get all transactions
GET http://localhost:4000/expense-api/expenses


###
//get expenses of any one user
GET http://localhost:4000/expense-api/expense/69f869dbc722ef0994ce403e


###
//update expense
PUT http://localhost:4000/expense-api/expense/69f9a46ca42f3be2aa34161a
Content-Type: application/json

{
  "title": "Dominos Pizza",
  "amount": 1500,
  "description": "Updated expense"
}


###
//delete expense
DELETE http://localhost:4000/expense-api/expense/69f98ff96f508117fe232486


###
//summary or dashboard

GET http://localhost:4000/expense-api/summary



###
//analytics
GET http://localhost:4000/expense-api/category-analytics



###
//monthly income vs expense
GET http://localhost:4000/expense-api/income-expense-analytics 


###
//predict next months expense
GET http://localhost:4000/expense-api/predict-expense


###
//AI insights
GET http://localhost:4000/expense-api/ai-insights
