//register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"user3",
    "email":"user3@gmail.com",
    "password":"user3",
    "monthlyBudget":"20000",
    "role":"USER"
}



###
// login

POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"user3@gmail.com",
    "password":"user3"
}


###
//logout

GET http://localhost:4000/common-api/logout 


###
//add expense
POST http://localhost:4000/expense-api/expense
Content-Type: application/json

{
  "title": "burger",
  "amount": 300,
  "type": "EXPENSE",
  "category": "FOOD",
  "description": "Tasty"
}



###
//Get all transactions
GET http://localhost:4000/expense-api/expenses


###
//get expenses of any one user
GET http://localhost:4000/expense-api/expense/69f869dbc722ef0994ce403e


###
//update expense
PUT http://localhost:4000/expense-api/expense/69f981e5ed7b935d4a3faeb4
Content-Type: application/json

{
  "title": "Dominos Pizza",
  "amount": 450,
  "description": "Updated expense"
}


###
//delete expense
DELETE http://localhost:4000/expense-api/expense/69f98ff96f508117fe232486


###
//summary or dashboard

GET http://localhost:4000/expense-api/summary



###
//analytics
GET http://localhost:4000/expense-api/category-analytics



###
//monthly income vs expense
GET http://localhost:4000/expense-api/income-expense-analytics 

###
//predict next month expense
GET http://localhost:4000/expense-api/predict-expense